on: [push, pull_request]
name: Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13.0'
    - name: Install hdf5
      run: make install-hdf5 1>/dev/null 2>&1
    - name: Run tests
      run: |
          make test path=./lsh